Sign in teachers using a one time password
DFE-Digital/apply-for-qualified-teacher-status pull request #816
Opened 2022-12-07 17:22 UTC by thomasleese

2022-12-09 14:00 UTC, gpeng requested changes
Looks good and works really well. So much better than those horrific links.

I spotted a couple of bits of content that need updating.

<img width="836" alt="Screenshot 2022-12-09 at 13 44 21" src="https://user-images.githubusercontent.com/5216/206718650-4874b97c-41ba-412d-acad-27a577491432.png">

<img width="721" alt="Screenshot 2022-12-09 at 13 41 37" src="https://user-images.githubusercontent.com/5216/206718592-726cbc89-bf70-44dd-90a9-a4962ede44fd.png">

There's a validation message missing too. Not sure we even want to validate fort that here 🤷 

<img width="753" alt="Screenshot 2022-12-09 at 13 42 43" src="https://user-images.githubusercontent.com/5216/206718821-14a4561b-9cbc-4980-83b5-f937e83154d4.png">

I also got a 500 page when I tried to enter a code that I'd already used. I didn't test the expiry as yet but reuse definitely errors.

2022-12-09 14:00 UTC, gpeng commented on app/forms/teachers/otp_form.rb
> +  EXPIRY_IN_MINUTES = 30.minutes
The email says 15 minutes

2022-12-09 14:00 UTC, gpeng commented on app/lib/devise/strategies/otp_authenticatable.rb
> +    unless resource && resource.secret_key.present?
Could we extract these predicates here and on 27 so we get:

```
fail!(:otp_invalid) and return if secret_key_absent? || otp_invalid?
```

2022-12-09 14:00 UTC, gpeng commented on app/views/teachers/mailer/otp.text.erb
> +The code will expire after 15 minutes.
15 minutes or 30?

2022-12-09 14:06 UTC, gpeng commented
Just spotted you've addressed some of that content stuff in the next PR. I'll check again on that one when this is merged.

2022-12-09 15:53 UTC, thomasleese commented
Thanks @gpeng I've addressed those comments.

> I also got a 500 page when I tried to enter a code that I'd already used. I didn't test the expiry as yet but reuse definitely errors.

Do you know if you took any other steps? I've got a test for this scenario and can't reproduce the problem myself: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/blob/5ce576166a198a124d23564cac447e0ce1026545/spec/system/teacher_interface/authentication_spec.rb#L94-L107

> Do we need a 'resend the code' link on the 'enter your code' page.

It might be a good idea, would be interested to see what the UCD team think. There is a back link that takes them to the sign in page again, and the failure page has a link allowing them to try again.

> Also I wonder if we should include the link back to that page in the email although I realise that will get us back into horrible link land.

Yeah, I'm not sure about this one, I'm happy to add it, but I suppose then users might think it's a link they have to click to sign in.

2022-12-12 11:52 UTC, gpeng approved these changes

2022-12-12 11:56 UTC, gpeng commented
> Do you know if you took any other steps? I've got a test for this scenario and can't reproduce the problem myself:

I can't recreate it now either 🤷

2022-12-14 10:15 UTC, merged